global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "cadastroagendamentocorte-job"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080", "host.docker.internal:8085"]
        labels:
          application: "cadastroagendamentocorte"